path: C:\Users\HP\Downloads\Object-Detection-Yolo\Object-Detection-Yolo\datasets

train: images/train  #train images(relative to 'path')
val: images/validation  #val images (relative to 'path')


names:
  0: Apple
  1: Orange
  2: Strawberry